// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB23Nq6ihv5Ioo-FtOeylu14mhtT3_Mwao',
    appId: '1:649591134192:web:86aada2a480d2606856f35',
    messagingSenderId: '649591134192',
    projectId: 'medibound-428805',
    authDomain: 'medibound-428805.firebaseapp.com',
    storageBucket: 'medibound-428805.appspot.com',
    measurementId: 'G-2SN3LDEK5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiTj0QrwDIk_DCgKX_eKAHiXBVGh7-RxI',
    appId: '1:649591134192:android:d9a3d530087815d5856f35',
    messagingSenderId: '649591134192',
    projectId: 'medibound-428805',
    storageBucket: 'medibound-428805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClV083ZIIfk6YqXXBIlfNT3PupRAjRyKU',
    appId: '1:649591134192:ios:3a88005771a45d2e856f35',
    messagingSenderId: '649591134192',
    projectId: 'medibound-428805',
    storageBucket: 'medibound-428805.appspot.com',
    iosBundleId: 'com.medibound',
  );
}
